language: objective-c
script:
    - xcodebuild -workspace JWAnimatedImage.xcworkspace -scheme 'JWAnimatedImage' -sdk iphonesimulator
    - xcodebuild -workspace JWAnimatedImage.xcworkspace -scheme 'JWAnimatedImageExampleâ€™ -sdk iphonesimulator
